### ISSUE TITLE
Python3 skin problem OpenAtv 6.5

### ISSUE THREAD

**Issue by pololoko111** [oerlgrey/KravenHD#4]
Hi nickersk.
The skin is not working for Oatv 6.5

openATV Enigma2 crash log

crashdate=pon lis 30 09:26:57 2020
compiledate=Nov 28 2020
skin=KravenHD/skin.xml
sourcedate=2020-11-22
branch=6.5
rev=2.8.0-22579-g53a3148
component=Enigma2

stbmodel=solo4k
stbmodel=dm8000
kernelcmdline=root=/dev/mmcblk0p4 rootwait rw rootflags=data=journal debug coherent_pool=2M bmem=633m@387m bmem=499m@2573m
nimsockets=NIM Socket 0:
imageversion=box_type=vusolo4k
imageissue=Welcome to openATV for %h

``[ePyObject] (PyObject_CallObject(<bound method Navigation.dispatchEvent of <Navigation.Navigation object at 0xb34a4fe8>>,(0,)) failed)
ADD Peer vuzero4k=vuzero4k.local:8001
ADD Peer vuzero4k=vuzero4k.local:8001
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap object at 0xa9f6dd30>>,('ColorActions', 'green')) failed)
[eDVBPESReader] ERROR reading PES (fd=80): Value too large for defined data type
[ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap object at 0xa9f6dd30>>,('ColorActions', 'green')) failed)

**Comment by nickersk** [comment]
hi, which 6.5 image do you use (own build or official test image)? from nextp3 or nextp3-ssl111 branch? (i cant see any error related to skin in your log, sorry) send full e2 log rather. thanks

**Comment by pololoko111** [comment]
I'm using the official image.

**log when I change channels**

> openATV Enigma2 crash log

crashdate=pon lis 30 09:24:47 2020
compiledate=Nov 28 2020
skin=KravenHD/skin.xml
sourcedate=2020-11-22
branch=6.5
rev=2.8.0-22579-g53a3148
component=Enigma2

stbmodel=solo4k
stbmodel=dm8000
kernelcmdline=root=/dev/mmcblk0p4 rootwait rw rootflags=data=journal debug coherent_pool=2M bmem=633m@387m bmem=499m@2573m
nimsockets=NIM Socket 0:
imageversion=box_type=vusolo4k
imageissue=Welcome to openATV for %h


[ePyObject] (PyObject_CallObject(<bound method Navigation.dispatchEvent of <Navigation.Navigation object at 0xb34a4fe8>>,(0,)) failed)


dmesg

<6>[    0.000000] Booting Linux on physical CPU 0x0
<5>[    0.000000] Linux version 3.14.28-1.8 (oe-user@oe-host) (gcc version 10.2.0 (GCC) ) #1 SMP Fri Nov 20 06:40:20 UTC 2020
<6>[    0.000000] CPU: ARMv7 Processor [420f00f3] revision 3 (ARMv7), cr=30c7387d
<6>[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, PIPT instruction cache
<6>[    0.000000] Machine model: BCM97366SFF_bad_MoCA
<6>[    0.000000] moving dtb from 0x000000000761c000 to 0x0000000000969180
<6>[    0.000000] bmem: Reserved 633 MiB at 0x0000000018300000
<6>[    0.000000] bmem: Reserved 499 MiB at 0x00000000a0d00000
<6>[    0.000000] cma: Reserved 16 MiB at 0x000000000f000000
<6>[    0.000000] Memory policy: Data cache writealloc
<7>[    0.000000] On node 0 totalpages: 524288
<7>[    0.000000] free_area_init_node: node 0, pgdat c092a000, node_mem_map cd7f2000
<7>[    0.000000]   Normal zone: 512 pages used for memmap
<7>[    0.000000]   Normal zone: 0 pages reserved
<7>[    0.000000]   Normal zone: 65536 pages, LIFO batch:15
<7>[    0.000000]   HighMem zone: 5632 pages used for memmap
<7>[    0.000000]   HighMem zone: 458752 pages, LIFO batch:31
<6>[    0.000000] MCP: Write pairing already disabled
<6>[    0.000000] PERCPU: Embedded 8 pages/cpu @cd7c2000 s9728 r8192 d14848 u32768
<7>[    0.000000] pcpu-alloc: s9728 r8192 d14848 u32768 alloc=8*4096
<7>[    0.000000] pcpu-alloc: [0] 0 [0] 1 
<4>[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 523776
<5>[    0.000000] Kernel command line: root=/dev/mmcblk0p4 rootwait rw rootflags=data=journal debug coherent_pool=2M bmem=633m@387m bmem=499m@2573m
<6>[    0.000000] PID hash table entries: 1024 (order: 0, 4096 bytes)
<6>[    0.000000] Dentry cache hash table entries: 32768 (order: 5, 131072 bytes)
<6>[    0.000000] Inode-cache hash table entries: 16384 (order: 4, 65536 bytes)
<4>[    0.000000] Memory: 891008K/2097152K available (6738K kernel code, 364K rwdata, 2032K rodata, 265K init, 199K bss, 1189760K reserved, 16384K cma-reserved, 671744K highmem)
<5>[    0.000000] Virtual kernel memory layout:
<5>[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
<5>[    0.000000]     fixmap  : 0xfff00000 - 0xfffe0000   ( 896 kB)
<5>[    0.000000]     vmalloc : 0xd0800000 - 0xff000000   ( 744 MB)
<5>[    0.000000]     lowmem  : 0xc0000000 - 0xd0000000   ( 256 MB)
<5>[    0.000000]     pkmap   : 0xbfe00000 - 0xc0000000   (   2 MB)
<5>[    0.000000]     modules : 0xbf000000 - 0xbfe00000   (  14 MB)
<5>[    0.000000]       .text : 0xc0008000 - 0xc0898cb8   (8772 kB)
<5>[    0.000000]       .init : 0xc0899000 - 0xc08db600   ( 266 kB)
<5>[    0.000000]       .data : 0xc08dc000 - 0xc09372c8   ( 365 kB)
<5>[    0.000000]        .bss : 0xc09372d0 - 0xc0969180   ( 200 kB)
<6>[    0.000000] Hierarchical RCU implementation.
<6>[    0.000000] 	RCU restricting CPUs from NR_CPUS=4 to nr_cpu_ids=2.
<6>[    0.000000] RCU: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=2
<6>[    0.000000] NR_IRQS:16 nr_irqs:16 16
<6>[    0.000000] irq_brcmstb_l2: registered L2 intc (mem: 0xfc403000, parent irq: 95)
<6>[    0.000000] irq_brcmstb_l2: registered L2 intc (mem: 0xfc441000, parent irq: 74)
<6>[    0.000000] irq_brcmstb_l2: registered L2 intc (mem: 0xfc410640, parent irq: 97)
<6>[    0.000000] irq_brcmstb_l2: registered L2 intc (mem: 0xfc4d1200, parent irq: 57)
<6>[    0.000000] Architected cp15 timer(s) running at 27.00MHz (virt).
<6>[    0.000004] sched_clock: 56 bits at 27MHz, resolution 37ns, wraps every 2545165795328ns
<6>[    0.000011] Switching to timer-based delay loop
<6>[    0.000273] Console: colour dummy device 80x30
<6>[    0.000295] Calibrating delay loop (skipped), value calculated using timer frequency.. 54.00 BogoMIPS (lpj=270000)
<6>[    0.000304] pid_max: default: 32768 minimum: 301
<6>[    0.000407] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
<6>[    0.000413] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
<6>[    0.006123] CPU: Testing write buffer coherency: ok
<6>[    0.006334] CPU0: update cpu_power 1024
<6>[    0.006342] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
<6>[    0.006395] Setting up static identity map for 0x671078 - 0x6710d0
<4>[    0.009349] CPU1: Booted secondary processor
<6>[    0.009373] CPU1: update cpu_power 1024
<6>[    0.009376] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
<6>[    0.009453] Brought up 2 CPUs
<6>[    0.009465] SMP: Total of 2 processors activated.
<6>[    0.009471] CPU: All CPU(s) started in SVC mode.
<6>[    0.009882] devtmpfs: initialized
<6>[    0.013411] VFP support v0.3: implementor 42 architecture 4 part 00 variant 0 rev 0
<6>[    0.014017] regulator-dummy: no parameters
<6>[    0.014175] NET: Registered protocol family 16
<6>[    0.016612] DMA: preallocated 2048 KiB pool for atomic coherent allocations
<6>[    0.016856] cpuidle: using governor ladder
<6>[    0.016861] cpuidle: using governor menu
<4>[    0.017970] irq: no irq domain found for /rdb/interrupt-controller@f040a580 !
<4>[    0.018067] irq: no irq domain found for /rdb/interrupt-controller@f0417280 !
<6>[    0.020000] syscon f0404000.syscon: regmap [mem 0xf0404000-0xf040452f] registered
<6>[    0.020107] syscon f0442400.syscon: regmap [mem 0xf0442400-0xf04427ff] registered
<6>[    0.020208] syscon f0462000.syscon: regmap [mem 0xf0462000-0xf04620ff] registered
<6>[    0.020303] syscon f0404100.syscon: regmap [mem 0xf0404100-0xf0404157] registered
<6>[    0.020398] syscon f0404158.syscon: regmap [mem 0xf0404158-0xf040418f] registered
<6>[    0.020502] syscon f0410700.syscon: regmap [mem 0xf0410700-0xf041070f] registered
<6>[    0.020595] syscon f0410710.syscon: regmap [mem 0xf0410710-0xf0410717] registered
<6>[    0.020695] syscon f0501004.syscon: regmap [mem 0xf0501004-0xf0501403] registered
<6>[    0.020788] syscon f0901004.syscon: regmap [mem 0xf0901004-0xf0901403] registered
<6>[    0.020882] syscon f0404080.syscon: regmap [mem 0xf0404080-0xf0404083] registered
<6>[    0.020974] syscon f04040a4.syscon: regmap [mem 0xf04040a4-0xf04040a7] registered
<6>[    0.021058] syscon f0440154.syscon: regmap [mem 0xf0440154-0xf0440157] registered
<6>[    0.021143] syscon f0440354.syscon: regmap [mem 0xf0440354-0xf0440357] registered
<6>[    0.021237] syscon f0440400.syscon: regmap [mem 0xf0440400-0xf0440403] registered
<6>[    0.021519] No ATAGs?
<6>[    0.021536] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
<6>[    0.021542] hw-breakpoint: maximum watchpoint size is 8 bytes.
<6>[    0.121950] brcm-pci f0470000.pcie: link down
<6>[    0.126797] bio: create slab <bio-0> at 0
<5>[    0.127275] SCSI subsystem initialized
<7>[    0.127371] libata version 3.00 loaded.
<6>[    0.127520] usbcore: registered new interface driver usbfs
<6>[    0.127555] usbcore: registered new interface driver hub
<6>[    0.127615] usbcore: registered new device driver usb
<6>[    0.127659] Linux video capture interface: v2.00
<6>[    0.127707] pps_core: LinuxPPS API ver. 1 registered
<6>[    0.127712] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
<6>[    0.127727] PTP clock support registered
<6>[    0.127994] Advanced Linux Sound Architecture Driver Initialized.
<6>[    0.128574] cfg80211: Calling CRDA to update world regulatory domain
<6>[    0.128712] Switched to clocksource arch_sys_counter
<5>[    0.128903] FS-Cache: Loaded
<4>[    0.133607] thermal thermal_zone0: failed to read out thermal zone 0
<6>[    0.133700] NET: Registered protocol family 2
<6>[    0.134123] TCP established hash table entries: 2048 (order: 1, 8192 bytes)
<6>[    0.134140] TCP bind hash table entries: 2048 (order: 2, 16384 bytes)
<6>[    0.134165] TCP: Hash tables configured (established 2048 bind 2048)
<6>[    0.134247] TCP: reno registered
<6>[    0.134256] UDP hash table entries: 256 (order: 1, 8192 bytes)
<6>[    0.134270] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
<6>[    0.134398] NET: Registered protocol family 1
<6>[    0.134625] RPC: Registered named UNIX socket transport module.
<6>[    0.134631] RPC: Registered udp transport module.
<6>[    0.134635] RPC: Registered tcp transport module.
<6>[    0.134639] RPC: Registered tcp NFSv4.1 backchannel transport module.
<7>[    0.134647] PCI: CLS 0 bytes, default 64
<6>[    0.134885] hw perfevents: enabled with ARMv7 Cortex-A15 PMU driver, 7 counters available
<6>[    0.135504] futex hash table entries: 512 (order: 3, 32768 bytes)
<4>[    0.136114] bounce pool size: 64 pages
<5>[    0.136522] FS-Cache: Netfs 'nfs' registered for caching
<5>[    0.136687] NFS: Registering the id_resolver key type
<5>[    0.136724] Key type id_resolver registered
<5>[    0.136729] Key type id_legacy registered
<6>[    0.136741] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
<6>[    0.136747] Installing knfsd (copyright (C) 1996 okir@monad.swb.de).
<5>[    0.136891] FS-Cache: Netfs 'cifs' registered for caching
<5>[    0.136950] Key type cifs.spnego registered
<6>[    0.137059] fuse init (API version 7.22)
<6>[    0.137169] SGI XFS with security attributes, realtime, large block/inode numbers, no debug enabled
<6>[    0.137468] msgmni has been set to 460
<6>[    0.138304] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
<6>[    0.138312] io scheduler noop registered
<6>[    0.138316] io scheduler deadline registered
<6>[    0.138335] io scheduler cfq registered (default)
<6>[    0.138581] brcm-gisb-arb f0400000.gisb-arb: registered mem: fc400000, irqs: 259, 260
<6>[    0.138999] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
<6>[    0.139995] f040b000.serial: ttyS0 at MMIO 0xf040b000 (irq = 108, base_baud = 5062500) is a 16550A
<6>[    0.962974] console [ttyS0] enabled
<6>[    0.966781] f040b040.serial: ttyS1 at MMIO 0xf040b040 (irq = 109, base_baud = 5062500) is a 16550A
<6>[    0.976080] f040b080.serial: ttyS2 at MMIO 0xf040b080 (irq = 110, base_baud = 5062500) is a 16550A
<6>[    0.987382] loop: module loaded
<3>[    0.990920] ahci strict-ahci.0: can't get clock
<6>[    0.995567] ahci strict-ahci.0: SSS flag set, parallel bus scan disabled
<6>[    1.018747] ahci strict-ahci.0: AHCI 0001.0300 32 slots 2 ports 6 Gbps 0x3 impl platform mode
<6>[    1.027284] ahci strict-ahci.0: flags: 64bit ncq sntf stag clo pmp slum part 
<6>[    1.036617] scsi0 : ahci_platform
<6>[    1.040204] scsi1 : ahci_platform
<6>[    1.043664] ata1: SATA max UDMA/133 mmio [mem 0xf046a000-0xf046aa9b] port 0x100 irq 72
<6>[    1.051600] ata2: SATA max UDMA/133 mmio [mem 0xf046a000-0xf046aa9b] port 0x180 irq 72
<6>[    1.060437] spi_brcmstb f0443400.spi: 1-lane output, 3-byte address
<6>[    1.066782] spi_brcmstb f0443400.spi: master is unqueued, this is deprecated
<4>[    1.074229] m25p80 spi32766.0: found mx25l3255e, expected m25p80
<6>[    1.080264] m25p80 spi32766.0: mx25l3255e (4096 Kbytes)
<5>[    1.085519] 5 ofpart partitions found on MTD device spi32766.0
<5>[    1.091366] Creating 5 MTD partitions on "spi32766.0":
<5>[    1.096512] 0x000000000000-0x000000200000 : "flash0.bolt"
<5>[    1.102473] 0x000000200000-0x000000210000 : "flash0.macadr"
<5>[    1.108515] 0x000000210000-0x000000220000 : "flash0.nvram"
<5>[    1.114467] 0x000000220000-0x000000230000 : "flash0.devtree"
<5>[    1.120609] 0x000000000000-0x000000400000 : "flash0"
<6>[    1.126411] libphy: Fixed MDIO Bus: probed
<6>[    1.131000] bcmgenet f0b60000.ethernet: GENET 4.3 EPHY: 0x1002
<6>[    1.138727] libphy: bcmgenet MII bus: probed
<6>[    1.161027] bcmgenet f0b60000.ethernet: configuring instance for internal PHY
<6>[    1.168821] e1000e: Intel(R) PRO/1000 Network Driver - 2.3.2-k
<6>[    1.174659] e1000e: Copyright(c) 1999 - 2013 Intel Corporation.
<6>[    1.299218] xhci-brcm: xHCI BRCM driver
<6>[    1.303174] xhci-brcm f0481000.xhci: xHCI Host Controller
<6>[    1.308722] xhci-brcm f0481000.xhci: new USB bus registered, assigned bus number 1
<6>[    1.316641] xhci-brcm f0481000.xhci: irq 116, io mem 0xf0481000
<6>[    1.323043] hub 1-0:1.0: USB hub found
<3>[    1.326821] hub 1-0:1.0: config failed, hub doesn't have any ports! (err -19)
<6>[    1.334119] xhci-brcm f0481000.xhci: xHCI Host Controller
<6>[    1.339631] xhci-brcm f0481000.xhci: new USB bus registered, assigned bus number 2
<6>[    1.347601] hub 2-0:1.0: USB hub found
<6>[    1.351381] hub 2-0:1.0: 2 ports detected
<6>[    1.355637] ehci-brcm: EHCI BRCM driver
<6>[    1.359645] ehci-brcm f0480300.ehci: EHCI Host Controller
<6>[    1.365157] ehci-brcm f0480300.ehci: new USB bus registered, assigned bus number 3
<6>[    1.382882] ehci-brcm f0480300.ehci: irq 112, io mem 0xf0480300
<6>[    1.408717] ehci-brcm f0480300.ehci: USB 2.0 started, EHCI 1.00
<6>[    1.415043] hub 3-0:1.0: USB hub found
<6>[    1.418830] hub 3-0:1.0: 1 port detected
<6>[    1.422963] ehci-brcm f0480500.ehci: EHCI Host Controller
<6>[    1.428456] ehci-brcm f0480500.ehci: new USB bus registered, assigned bus number 4
<6>[    1.446169] ehci-brcm f0480500.ehci: irq 113, io mem 0xf0480500
<6>[    1.468782] ehci-brcm f0480500.ehci: USB 2.0 started, EHCI 1.00
<6>[    1.475084] hub 4-0:1.0: USB hub found
<6>[    1.478871] hub 4-0:1.0: 1 port detected
<6>[    1.482996] ehci-brcm f0490300.ehci: EHCI Host Controller
<6>[    1.488500] ehci-brcm f0490300.ehci: new USB bus registered, assigned bus number 5
<6>[    1.506204] ehci-brcm f0490300.ehci: irq 118, io mem 0xf0490300
<6>[    1.528716] ehci-brcm f0490300.ehci: USB 2.0 started, EHCI 1.00
<6>[    1.535020] hub 5-0:1.0: USB hub found
<6>[    1.539835] hub 5-0:1.0: 1 port detected
<6>[    1.543973] ehci-brcm f0490500.ehci: EHCI Host Controller
<6>[    1.549481] ehci-brcm f0490500.ehci: new USB bus registered, assigned bus number 6
<6>[    1.567176] ehci-brcm f0490500.ehci: irq 119, io mem 0xf0490500
<6>[    1.588715] ehci-brcm f0490500.ehci: USB 2.0 started, EHCI 1.00
<6>[    1.595035] hub 6-0:1.0: USB hub found
<6>[    1.599125] hub 6-0:1.0: 1 port detected
<6>[    1.603237] ohci-brcm: OHCI BRCM driver
<6>[    1.607220] ohci-brcm f0480400.ohci: BRCM OHCI controller
<6>[    1.612731] ohci-brcm f0480400.ohci: new USB bus registered, assigned bus number 7
<6>[    1.620359] ohci-brcm f0480400.ohci: irq 114, io mem 0xf0480400
<6>[    1.628728] ata1: SATA link up 1.5 Gbps (SStatus 113 SControl 300)
<6>[    1.680166] ata1.00: ATA-8: TOSHIBA MK1665GSX H, GJ001Q, max UDMA/100
<6>[    1.683151] hub 7-0:1.0: USB hub found
<6>[    1.683172] hub 7-0:1.0: 1 port detected
<6>[    1.683412] ohci-brcm f0480600.ohci: BRCM OHCI controller
<6>[    1.683521] ohci-brcm f0480600.ohci: new USB bus registered, assigned bus number 8
<6>[    1.683573] ohci-brcm f0480600.ohci: irq 115, io mem 0xf0480600
<6>[    1.713197] ata1.00: 312581808 sectors, multi 16: LBA48 NCQ (depth 31/32)
<6>[    1.720662] ata1.00: configured for UDMA/100
<5>[    1.725191] scsi 0:0:0:0: Direct-Access     ATA      TOSHIBA MK1665GS GJ00 PQ: 0 ANSI: 5
<5>[    1.733758] sd 0:0:0:0: [sda] 312581808 512-byte logical blocks: (160 GB/149 GiB)
<5>[    1.733761] sd 0:0:0:0: Attached scsi generic sg0 type 0
<6>[    1.743200] hub 8-0:1.0: USB hub found
<6>[    1.743222] hub 8-0:1.0: 1 port detected
<6>[    1.743502] ohci-brcm f0490400.ohci: BRCM OHCI controller
<6>[    1.743619] ohci-brcm f0490400.ohci: new USB bus registered, assigned bus number 9
<6>[    1.743665] ohci-brcm f0490400.ohci: irq 120, io mem 0xf0490400
<5>[    1.773443] sd 0:0:0:0: [sda] Write Protect is off
<7>[    1.778243] sd 0:0:0:0: [sda] Mode Sense: 00 3a 00 00
<5>[    1.783362] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
<6>[    1.803117] hub 9-0:1.0: USB hub found
<6>[    1.806892] hub 9-0:1.0: 1 port detected
<6>[    1.811068] ohci-brcm f0490600.ohci: BRCM OHCI controller
<6>[    1.816577] ohci-brcm f0490600.ohci: new USB bus registered, assigned bus number 10
<6>[    1.824300] ohci-brcm f0490600.ohci: irq 121, io mem 0xf0490600
<6>[    1.843758]  sda: sda1
<5>[    1.846691] sd 0:0:0:0: [sda] Attached SCSI disk
<6>[    1.888748] usb 5-1: new high-speed USB device number 2 using ehci-brcm
<6>[    1.893139] hub 10-0:1.0: USB hub found
<6>[    1.893160] hub 10-0:1.0: 1 port detected
<6>[    1.893371] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
<6>[    1.893383] ehci-pci: EHCI PCI platform driver
<6>[    1.893432] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
<6>[    1.893440] ohci-pci: OHCI PCI platform driver
<6>[    1.893597] usbcore: registered new interface driver usb-storage
<6>[    1.893729] mousedev: PS/2 mouse device common for all mice
<6>[    1.936646] i2c /dev entries driver
<6>[    1.940438] IR NEC protocol handler initialized
<6>[    1.944974] IR RC5(x) protocol handler initialized
<6>[    1.949788] IR RC6 protocol handler initialized
<6>[    1.954323] IR JVC protocol handler initialized
<6>[    1.958866] IR Sony protocol handler initialized
<6>[    1.963492] IR RC5 (streamzap) protocol handler initialized
<6>[    1.969079] IR SANYO protocol handler initialized
<6>[    1.973787] IR MCE Keyboard/mouse protocol handler initialized
<4>[    1.979696] cpufreq_cpu0: failed to get cpu0 regulator: -19
<6>[    1.985459] sdhci: Secure Digital Host Controller Interface driver
<6>[    1.991659] sdhci: Copyright(c) Pierre Ossman
<6>[    1.996020] sdhci-pltfm: SDHCI platform and OF driver helper
<6>[    2.002814] mmc0: no vqmmc regulator found
<6>[    2.006918] mmc0: no vmmc regulator found
<6>[    2.048724] mmc0: SDHCI controller on f0440000.sdhci [f0440000.sdhci] using ADMA
<6>[    2.057203] mmc1: no vqmmc regulator found
<6>[    2.061312] mmc1: no vmmc regulator found
<6>[    2.108723] mmc1: SDHCI controller on f0440200.sdhci [f0440200.sdhci] using ADMA
<6>[    2.116268] hidraw: raw HID events driver (C) Jiri Kosina
<6>[    2.118733] ata2: SATA link down (SStatus 0 SControl 300)
<6>[    2.127247] usbcore: registered new interface driver usbhid
<6>[    2.132834] usbhid: USB HID core driver
<6>[    2.137796] TCP: cubic registered
<6>[    2.141200] NET: Registered protocol family 10
<6>[    2.146283] NET: Registered protocol family 17
<5>[    2.150978] Key type dns_resolver registered
<5>[    2.155303] Registering SWP/SWPB emulation handler
<6>[    2.160425] regulator-dummy: disabling
<6>[    2.170323] ALSA device list:
<6>[    2.173314]   No soundcards found.
<6>[    2.177020] Waiting for root device /dev/mmcblk0p4...
<6>[    2.412382] mmc1: BKOPS_EN bit is not set
<6>[    2.422621] mmc1: new high speed MMC card at address 0001
<6>[    2.428329] mmcblk0: mmc1:0001 4FPD3R 3.64 GiB 
<6>[    2.432988] mmcblk0boot0: mmc1:0001 4FPD3R partition 1 4.00 MiB
<6>[    2.439023] mmcblk0boot1: mmc1:0001 4FPD3R partition 2 4.00 MiB
<6>[    2.448100]  mmcblk0: p1 p2 p3 p4
<6>[    2.452564]  mmcblk0boot1: unknown partition table
<6>[    2.457982]  mmcblk0boot0: unknown partition table
<4>[    2.509296] EXT4-fs: Warning: mounting with data=journal disables delayed allocation and O_DIRECT support!
<6>[    2.524812] EXT4-fs (mmcblk0p4): mounted filesystem with journalled data mode. Opts: data=journal
<6>[    2.533733] VFS: Mounted root (ext4 filesystem) on device 179:4.
<6>[    2.541055] devtmpfs: mounted
<6>[    2.544324] Freeing unused kernel memory: 264K (c0899000 - c08db000)
<6>[    3.494499] EXT4-fs (sda1): mounted filesystem with writeback data mode. Opts: (null)
<6>[    4.118747] usb 5-1: reset high-speed USB device number 2 using ehci-brcm
<6>[    4.278416] ieee80211 phy0: rt2x00_set_rt: Info - RT chipset 5392, rev 0223 detected
<6>[    4.314292] ieee80211 phy0: rt2x00_set_rf: Info - RF chipset 5372 detected
<7>[    4.322425] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
<6>[    4.350445] usbcore: registered new interface driver rt2800usb
<6>[    4.421612] EXT4-fs (mmcblk0p4): re-mounted. Opts: nodelalloc,data=journal
<5>[    4.727776] random: dd urandom read with 115 bits of entropy available
<5>[    5.105755] random: nonblocking pool is initialized
<4>[    5.742332] procmk_init
<4>[    5.748419] bcm_event: module license 'Proprietary' taints kernel.
<4>[    5.754656] Disabling lock debugging due to kernel taint
<6>[    9.039420] DVB: registering new adapter (_vuplus_solo4k_)
<4>[    9.529387] bcm7376: hotplug_callback(): 
<4>[    9.529387] Hotplug - status.connected 1:0:1
<4>[    9.536385] bcm7376: hotplug_callback(): 
<4>[    9.536385] Hotplug - connecting HDMI to display 0xe
<6>[    9.828717] brcm_demux_init: $Id: bcm_demux.c,v 0.7 $
<4>[   10.018911] [MPVR]: >> misc_pvr_init
<4>[   10.040682] [VID]: 6bcm7335_video_init
<4>[   10.104267] [AUD]: 6bcm7335_audio_init
<4>[   10.109274] [AUD]: >> bcm_audio_capture_init
<4>[   10.128922] qam=0, ofdm=0, satellite=1
<6>[   10.138247] BRCM brcm_dvb0: DVB: registering adapter 0 frontend 0 (Vuplus FE)...
<4>[   10.146944] qam=0, ofdm=0, satellite=1
<6>[   10.153222] BRCM brcm_dvb0: DVB: registering adapter 0 frontend 0 (Vuplus FE)...
<4>[   10.163735] qam=0, ofdm=0, satellite=1
<6>[   10.168218] BRCM brcm_dvb0: DVB: registering adapter 0 frontend 0 (Vuplus FE)...
<4>[   10.176590] qam=0, ofdm=0, satellite=1
<6>[   10.181110] BRCM brcm_dvb0: DVB: registering adapter 0 frontend 0 (Vuplus FE)...
<4>[   10.191324] qam=0, ofdm=0, satellite=1
<6>[   10.195836] BRCM brcm_dvb0: DVB: registering adapter 0 frontend 0 (Vuplus FE)...
<4>[   10.207823] qam=0, ofdm=0, satellite=1
<6>[   10.212346] BRCM brcm_dvb0: DVB: registering adapter 0 frontend 0 (Vuplus FE)...
<4>[   10.222067] qam=0, ofdm=0, satellite=1
<6>[   10.226609] BRCM brcm_dvb0: DVB: registering adapter 0 frontend 0 (Vuplus FE)...
<4>[   10.235879] qam=0, ofdm=0, satellite=1
<6>[   10.240921] BRCM brcm_dvb0: DVB: registering adapter 0 frontend 0 (Vuplus FE)...
<4>[   10.250680] bcm7376: bcm7335_frontend_init(): vtuner1 : 9
<4>[   10.359381] BKNI_P_GetTrackAllocEntry_resize: resizing from 5376->8704
<4>[   10.367311] BKNI_Malloc(linuxkernel) top users:
<4>[   10.367311]     blocks,   bytes, filename:line
<4>[   10.376356]       1291,  282224, BSEAV/lib/utils/balloc.c:31
<6>[   10.469899] input: dreambox advanced remote control (native) as /devices/virtual/input/input0
<6>[   10.501194] [LCD]: registered
<6>[   11.048989] [CI]: registered ci0
<6>[   11.089270] [CI]: CI interface initialised
<6>[   11.089270] 
<6>[   11.149031] [DFP]: registered dbox fp
<6>[   11.169551] [SC]: registered sci0
<6>[   11.175025] [SC]: registered sci1
<4>[   12.798736] system_time_set wakeup mode get 
<4>[   12.858740] system_time_set wakeup mode get 0xc4
<4>[   13.149693] [VID]: VIDEO_SET_STREAMTYPE 0 
<4>[   13.157588] [VID]: VIDEO_SELECT_SOURCE 1  0
<4>[   13.162420] [VID]: VIDEO_PLAY 1  2 0
<4>[   13.171478] [VID]: VIDEO_CONTINUE 1  1 
<4>[   13.175337] [VID]: VIDEO_CLEAR_BUFFER 1  1 0
<4>[   13.450965] [VID]: VIDEO_STOP 0  1
<4>[   13.455516] [VID]: VIDEO_SELECT_SOURCE 0  0
<6>[   13.518731] f0b60000.etherne:01: Broadcom BCM7366 PHY revision: 0x10, patch: 2
<6>[   13.527632] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
<6>[   15.518807] libphy: f0b60000.etherne:01 - Link is Down
<6>[   16.883896] libphy: f0b60000.etherne:01 - Link is Up - 1000/Full
<6>[   16.890090] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
<6>[   21.189515] Bluetooth: Core ver 2.18
<6>[   21.193995] NET: Registered protocol family 31
<6>[   21.199006] Bluetooth: HCI device and connection manager initialized
<6>[   21.205709] Bluetooth: HCI socket layer initialized
<6>[   21.210634] Bluetooth: L2CAP socket layer initialized
<6>[   21.215799] Bluetooth: SCO socket layer initialized
<4>[   23.425017] [VID]: VIDEO_SET_STREAMTYPE 0 
<4>[   23.429523] [VID]: VIDEO_SELECT_SOURCE 1  0
<4>[   23.433781] [VID]: VIDEO_PLAY 1  2 0
<4>[   23.442734] [VID]: VIDEO_CONTINUE 1  1 
<4>[   23.446581] [VID]: VIDEO_CLEAR_BUFFER 1  1 0
<4>[   23.722931] [VID]: VIDEO_STOP 0  1
<4>[   23.727404] [VID]: VIDEO_SELECT_SOURCE 0  0
<3>[   23.979305] [SC]: !!!unknown cmd 0x540b
<4>[   24.574196] UDF-fs: warning (device mmcblk0p1): udf_fill_super: No partition found (2)
<4>[   24.642513] UDF-fs: warning (device mmcblk0p1): udf_fill_super: No partition found (2)
<4>[   24.691130] UDF-fs: warning (device mmcblk0p3): udf_fill_super: No partition found (2)
<4>[   24.750317] UDF-fs: warning (device mmcblk0p3): udf_fill_super: No partition found (2)
<3>[   25.392404] [DFP]: unknown cmd 0x5401
<3>[   25.396572] [DFP]: unknown cmd 0x5401
<4>[   29.010385] [AUD]: AUDIO_SET_MUTE 0 
<4>[   29.109806] [AUD]: AUDIO_SET_MIXER -892346736 
<4>[   29.114266] [AUD]: AUDIO_SET_MIXER : amixl 0, amixr 0
<4>[   29.119368] [AUD]: AUDIO_SET_MIXER : next left volume 0, right volume 0
<4>[   29.125996] [AUD]: AUDIO_SET_MIXER : next left volume -70, right volume -70
<3>[   34.625716] [DFP]: unknown cmd 0x5401
<3>[   34.629598] [DFP]: unknown cmd 0x5401
<4>[   36.867012] [AUD]: AUDIO_SET_MIXER -892346736 
<4>[   36.871536] [AUD]: AUDIO_SET_MIXER : amixl 35, amixr 35
<4>[   36.876776] [AUD]: AUDIO_SET_MIXER : next left volume -70, right volume -70
<4>[   36.883790] [AUD]: AUDIO_SET_MIXER : next left volume -2570, right volume -2570
<4>[   37.228991] FE tune
<4>[   37.437017] [AUD]: AUDIO_SELECT_SOURCE 0 
<4>[   37.441629] [AUD]: AUDIO_SET_BYPASS_MODE 1 
<4>[   37.446125] [AUD]: downmix 0 state : 0
<4>[   37.450020] [AUD]: AUDIO_PAUSE 1 
<4>[   37.453373] [AUD]: AUDIO_PLAY 1 decoder start : 0
<4>[   37.459851] [VID]: VIDEO_SELECT_SOURCE 0  0
<4>[   37.464409] [VID]: VIDEO_GET_SIZE src w: 0 h:0 display w:0 h:0
<4>[   37.470304] [VID]: VIDEO_GET_SIZE aspect: 1 0
<4>[   37.474707] [VID]: VIDEO_SET_STREAMTYPE 1 
<4>[   37.478944] [VID]: VIDEO_FREEZE -1092765948  0
<4>[   37.483599] [VID]: VIDEO_PLAY -1092765948  5 2
<4>[   37.495530] [VID]: VIDEO_SLOWMOTION 0    1
<4>[   37.500959] [VID]: VIDEO_FAST_FORWARD 0    1 0
<4>[   37.506325] [VID]: VIDEO_CONTINUE 0  1 
<4>[   37.511725] [AUD]: AUDIO_CONTINUE 0 1 aph=0xcace7c80
<4>[   37.517847] [AUD]: Mute : 0
<4>[   37.522846] [AUD]: AUDIO_CHANNEL_SELECT 0 
<3>[   49.446110] [DFP]: unknown cmd 0x5401
<3>[   49.449851] [DFP]: unknown cmd 0x5401
<3>[   49.555615] [DFP]: unknown cmd 0x5401
<3>[   49.559357] [DFP]: unknown cmd 0x5401
<4>[  778.444768] [VID]: VIDEO_STOP 1  1
<4>[  778.448645] [AUD]: AUDIO_STOP 6500400 
<4>[  778.476931] [AUD]: AUDIO_CONTINUE 0 0 aph=0x0
<4>[  778.481501] [AUD]: AUDIO_CONTINUE aph=0 0 0
<4>[  778.567189] FE tune
<4>[  778.767735] [AUD]: AUDIO_SELECT_SOURCE 0 
<4>[  778.772918] [AUD]: AUDIO_SET_BYPASS_MODE 1 
<4>[  778.777381] [AUD]: downmix 0 state : 0
<4>[  778.781235] [AUD]: AUDIO_PAUSE 1 
<4>[  778.784657] [AUD]: AUDIO_PLAY 1 decoder start : 0
<4>[  778.790381] [VID]: VIDEO_SELECT_SOURCE 0  0
<4>[  778.794690] [VID]: VIDEO_SET_STREAMTYPE 1 
<4>[  778.799100] [VID]: VIDEO_FREEZE -1092765940  0
<4>[  778.803602] [VID]: VIDEO_PLAY -1092765940  5 2
<4>[  778.815413] [VID]: VIDEO_SLOWMOTION 0    1
<4>[  778.820789] [VID]: VIDEO_FAST_FORWARD 0    1 0
<4>[  778.826601] [VID]: VIDEO_CONTINUE 0  1 
<4>[  778.831666] [AUD]: AUDIO_CONTINUE 0 1 aph=0xcace7480
<4>[  778.837896] [AUD]: Mute : 0
<4>[  778.847896] [VID]: VIDEO_GET_SIZE src w: 0 h:0 display w:0 h:0
<4>[  778.854949] [VID]: VIDEO_GET_SIZE aspect: 1 0
<4>[  799.117513] [VID]: VIDEO_STOP 1  1
<4>[  799.120986] [AUD]: AUDIO_STOP 14677824 
<4>[  799.149335] [AUD]: AUDIO_CONTINUE 0 0 aph=0x0
<4>[  799.153719] [AUD]: AUDIO_CONTINUE aph=0 0 0
<4>[  799.266259] FE tune
<4>[  799.467665] [AUD]: AUDIO_SELECT_SOURCE 0 
<4>[  799.472877] [AUD]: AUDIO_SET_BYPASS_MODE 1 
<4>[  799.477325] [AUD]: downmix 0 state : 0
<4>[  799.481593] [AUD]: AUDIO_PAUSE 1 
<4>[  799.484960] [AUD]: AUDIO_PLAY 1 decoder start : 0
<4>[  799.490665] [VID]: VIDEO_SELECT_SOURCE 0  0
<4>[  799.495103] [VID]: VIDEO_SET_STREAMTYPE 1 
<4>[  799.499557] [VID]: VIDEO_FREEZE -1092765940  0
<4>[  799.504125] [VID]: VIDEO_PLAY -1092765940  5 2
<4>[  799.515990] [VID]: VIDEO_SLOWMOTION 0    1
<4>[  799.521383] [VID]: VIDEO_FAST_FORWARD 0    1 0
<4>[  799.527167] [VID]: VIDEO_CONTINUE 0  1 
<4>[  799.532240] [AUD]: AUDIO_CONTINUE 0 1 aph=0xcace7800
<4>[  799.538675] [AUD]: Mute : 0
<4>[  799.548214] [VID]: VIDEO_GET_SIZE src w: 0 h:0 display w:0 h:0
<4>[  799.555588] [VID]: VIDEO_GET_SIZE aspect: 1 0
<4>[ 1113.383258] [VID]: VIDEO_STOP 1  1
<4>[ 1113.386788] [AUD]: AUDIO_STOP 14360648 
<4>[ 1113.414969] [AUD]: AUDIO_CONTINUE 0 0 aph=0x0
<4>[ 1113.419338] [AUD]: AUDIO_CONTINUE aph=0 0 0
<4>[ 1115.684314] [VID]: VIDEO_SET_STREAMTYPE 0 
<4>[ 1115.688920] [VID]: VIDEO_SELECT_SOURCE 1  0
<4>[ 1115.693623] [VID]: VIDEO_PLAY 1  2 0
<4>[ 1115.702596] [VID]: VIDEO_CONTINUE 1  1 
<4>[ 1115.706529] [VID]: VIDEO_CLEAR_BUFFER 1  1 0
<4>[ 1115.981858] [VID]: VIDEO_STOP 0  1
<4>[ 1115.986465] [VID]: VIDEO_SELECT_SOURCE 0  0
<4>[ 1116.485901] UDF-fs: warning (device mmcblk0p1): udf_fill_super: No partition found (2)
<4>[ 1116.546144] UDF-fs: warning (device mmcblk0p1): udf_fill_super: No partition found (2)
<4>[ 1116.592287] UDF-fs: warning (device mmcblk0p3): udf_fill_super: No partition found (2)
<4>[ 1116.650014] UDF-fs: warning (device mmcblk0p3): udf_fill_super: No partition found (2)
<3>[ 1117.181952] [DFP]: unknown cmd 0x5401
<3>[ 1117.185687] [DFP]: unknown cmd 0x5401
<4>[ 1119.562683] [AUD]: AUDIO_SET_MUTE 0 
<4>[ 1119.662489] [AUD]: AUDIO_SET_MIXER -891863408 
<4>[ 1119.666956] [AUD]: AUDIO_SET_MIXER : amixl 0, amixr 0
<4>[ 1119.672047] [AUD]: AUDIO_SET_MIXER : next left volume -2570, right volume -2570
<4>[ 1119.679536] [AUD]: AUDIO_SET_MIXER : next left volume -70, right volume -70
<3>[ 1123.496089] [DFP]: unknown cmd 0x5401
<3>[ 1123.499892] [DFP]: unknown cmd 0x5401
<4>[ 1125.872092] [AUD]: AUDIO_SET_MIXER -891863408 
<4>[ 1125.876574] [AUD]: AUDIO_SET_MIXER : amixl 35, amixr 35
<4>[ 1125.881879] [AUD]: AUDIO_SET_MIXER : next left volume -70, right volume -70
<4>[ 1125.889199] [AUD]: AUDIO_SET_MIXER : next left volume -2570, right volume -2570

**log when I want to save the changes with the green button**

>[ePyObject] (PyObject_CallObject(<bound method Navigation.dispatchEvent of <Navigation.Navigation object at 0xb34a4fe8>>,(0,)) failed)
ADD Peer vuzero4k=vuzero4k.local:8001
ADD Peer vuzero4k=vuzero4k.local:8001
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap object at 0xa9f6dd30>>,('ColorActions', 'green')) failed)
[eDVBPESReader] ERROR reading PES (fd=80): Value too large for defined data type
[ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap object at 0xa9f6dd30>>,('ColorActions', 'green')) failed)


dmesg

<4>[ 1136.653665] FE tune
<4>[ 1136.859722] [AUD]: AUDIO_SELECT_SOURCE 0 
<4>[ 1136.864537] [AUD]: AUDIO_SET_BYPASS_MODE 1 
<4>[ 1136.868922] [AUD]: downmix 0 state : 0
<4>[ 1136.872993] [AUD]: AUDIO_PAUSE 1 
<4>[ 1136.876316] [AUD]: AUDIO_PLAY 1 decoder start : 0
<4>[ 1136.882087] [VID]: VIDEO_SELECT_SOURCE 0  0
<4>[ 1136.886360] [VID]: VIDEO_GET_SIZE src w: 1280 h:720 display w:1280 h:720
<4>[ 1136.893104] [VID]: VIDEO_GET_SIZE aspect: 1 3
<4>[ 1136.898072] [VID]: VIDEO_SET_STREAMTYPE 1 
<4>[ 1136.902420] [VID]: VIDEO_FREEZE -1092622516  0
<4>[ 1136.906883] [VID]: VIDEO_PLAY -1092622516  5 2
<4>[ 1136.919320] [VID]: VIDEO_SLOWMOTION 0    1
<4>[ 1136.924412] [VID]: VIDEO_FAST_FORWARD 0    1 0
<4>[ 1136.930041] [VID]: VIDEO_CONTINUE 0  1 
<4>[ 1136.935396] [AUD]: AUDIO_CONTINUE 0 1 aph=0xcace7480
<4>[ 1136.941670] [AUD]: Mute : 0
<4>[ 1136.946874] [AUD]: AUDIO_CHANNEL_SELECT 0

**Comment by nickersk** [comment]
can you paste output of shell command opkg list|grep kravenhd here please?

**Comment by pololoko111** [comment]
root@vusolo4k:~# opkg list|grep kravenhd
enigma2-plugin-skins-kravenhd - 7.8.x+git110+ade14fa-r0 - KravenHD Skin for Enig                                                                                        ma2 by Team Kraven

**Comment by nickersk** [comment]
ok, so version is recent. seems some specific setting is causing crash when saving. this should be noticed somewhere in log ... i develop on vusolose and i am unable to reproduce this behaviour.

**Comment by pololoko111** [comment]
could you please check this log?

[enigma2_crash_1606733857.log](https://github.com/oerlgrey/KravenHD/files/5615546/enigma2_crash_1606733857.log)

**Comment by nickersk** [comment]
according to config.py seems something with slider setting ... yep, antialias value is saved incorrectly as str not int ... going to take a look @ this. thx for reporting.

**Comment by pololoko111** [comment]
Thank you very much. The old 6.4 settings were a problem. Clean image install helped.

**Comment by nickersk** [comment]
@pololoko111 configs should be fixed definitelly: https://github.com/oerlgrey/KravenHD/commit/b8ba3bd92aad7116ad366d1d10b56e4b11252190
thx for reporting.

**Comment by pololoko111** [comment]
Hi @nickersk 
Still crashes after updating
[enigma2_crash_1606853522.log](https://github.com/oerlgrey/KravenHD/files/5625214/enigma2_crash_1606853522.log)

**Comment by nickersk** [comment]
seems to be another issue, @pololoko111 this crash comes with dvb-s settings, no problem with dvb-t... should be fixed here https://github.com/oerlgrey/KravenHD/commit/9a8f721fc0ec5947092c3285b8bb101ba8ffec67

**Comment by pololoko111** [comment]
Hi.
If you select the gradient texture texture options it is a crash.
Without this option, everything works fine. Thanks for the corrections.
[enigma2_crash_1607069827.log](https://github.com/oerlgrey/KravenHD/files/5641524/enigma2_crash_1607069827.log)
![gradient](https://user-images.githubusercontent.com/37630415/101139440-74603600-3609-11eb-9a52-f3c3f775e84a.jpg)

**Comment by nickersk** [comment]
thx, should be fixed now.

**Comment by pololoko111** [comment]
Perfect. Thank you very much.
